/**
 * The Leistungen page content: four sections, fourteen groups, and the
 * individual services under each. Rendered by `app/services/page.tsx`.
 *
 * Only the section number is shown on the page, and it is stored rather than
 * derived from array position so a section can be reordered without silently
 * renumbering the others — it is part of the copy the client signed off on.
 */

export type ServiceGroup = {
    /**
     * Position in the source document ("01"–"14"). Not rendered — the page
     * numbers sections only — but kept as a stable key and so a group can be
     * traced back to the client's list.
     */
    number: string;
    title: string;
    items: readonly string[];
};

export type ServiceSection = {
    /** Two-digit label shown before the section title in the page header. */
    number: string;
    title: string;
    /** Looping clip in the sticky column beside the section's groups. */
    video: string;
    /** First frame of `video`, held until the clip is fetched and playing. */
    poster: string;
    groups: readonly ServiceGroup[];
};

export const serviceSections: readonly ServiceSection[] = [
    {
        number: "01",
        title: "Strategie, Marke & Design",
        video: "/services/services-01.mp4",
        poster: "/images/services-01-poster.webp",
        groups: [
            {
                number: "01",
                title: "Strategie & Beratung",
                items: [
                    "Digitale Strategie",
                    "Markenpositionierung",
                    "Zielgruppenanalyse",
                    "Wettbewerbsanalyse",
                    "Customer Journey",
                    "Conversion-Strategie",
                    "Website-Struktur",
                    "Content-Planung",
                    "Kampagnen-Konzept",
                    "Marketing-Roadmap",
                    "Projektplanung",
                    "Beratung für digitale Transformation",
                ],
            },
            {
                number: "02",
                title: "Webdesign & UX/UI",
                items: [
                    "Corporate Websites",
                    "Landingpages",
                    "Onepager",
                    "UX-Konzept",
                    "UI-Design",
                    "Wireframes",
                    "Designsysteme",
                    "Mobile Design",
                    "Responsive Design",
                    "Interaktive Layouts",
                    "Conversion-orientierte Seitenstruktur",
                    "User Journey",
                    "Navigationskonzept",
                    "Prototyping",
                    "Design für WordPress",
                    "Design für Webflow",
                    "Design für E-Commerce",
                    "Design für Arztpraxen, Kliniken und lokale Unternehmen",
                ],
            },
            {
                number: "03",
                title: "Web Development",
                items: [
                    "WordPress Entwicklung",
                    "Webflow Entwicklung",
                    "Elementor Websites",
                    "Bricks Websites",
                    "Custom WordPress Lösungen",
                    "Frontend Development",
                    "CMS-Struktur",
                    "ACF-Strukturen",
                    "Individuelle Inhaltsmodule",
                    "Technische Umsetzung von Designs",
                    "Responsive Umsetzung",
                    "Performance-Optimierung",
                    "Pagespeed-Optimierung",
                    "Formulare & Anfrageprozesse",
                    "Mehrsprachige Websites",
                    "Technische SEO-Grundlagen",
                    "Tracking-Integration",
                    "Cookie-Consent-Integration",
                    "Wartbare Seitenarchitektur",
                ],
            },
            {
                number: "04",
                title: "E-Commerce & digitale Systeme",
                items: [
                    "WooCommerce Shops",
                    "Shopify-Strukturen",
                    "Produktseiten",
                    "Kategoriestrukturen",
                    "Filterlogik",
                    "Checkout-Optimierung",
                    "Produktverwaltung",
                    "Digitale Produktpräsentation",
                    "Buchungssysteme",
                    "Terminbuchung",
                    "Kursbuchung",
                    "Academy-Strukturen",
                    "Event-Anmeldung",
                    "Service-Anfragen",
                    "Mitgliederbereiche",
                    "Kundenbereiche",
                    "Zahlungsintegration",
                    "E-Mail-Automationen",
                    "Digitale Verkaufslogik",
                ],
            },
        ],
    },
    {
        number: "02",
        title: "Websites, Systeme & Development",
        video: "/services/services-02.mp4",
        poster: "/images/services-02-poster.webp",
        groups: [
            {
                number: "05",
                title: "SEO & Sichtbarkeit",
                items: [
                    "Technisches SEO",
                    "Keyword-Recherche",
                    "OnPage-Optimierung",
                    "SEO-Struktur",
                    "Meta-Titel & Meta-Beschreibungen",
                    "Content-Optimierung",
                    "Lokales SEO",
                    "Google-Business-Optimierung",
                    "SEO für Arztpraxen",
                    "SEO für lokale Unternehmen",
                    "SEO für Dienstleister",
                    "SEO für E-Commerce",
                    "Interne Verlinkung",
                    "Indexierungsprüfung",
                    "Pagespeed-Analyse",
                    "Wettbewerbsanalyse",
                    "SEO-Monitoring",
                    "SEO-Reporting",
                    "Content-Strategie",
                    "FAQ-Strukturen",
                    "Schema Markup",
                ],
            },
            {
                number: "06",
                title: "Google Ads & Performance Marketing",
                items: [
                    "Google Ads Kampagnen",
                    "Search Ads",
                    "Performance Max",
                    "Lokale Kampagnen",
                    "Keyword-Setup",
                    "Anzeigenstruktur",
                    "Kampagnenerstellung",
                    "Budgetplanung",
                    "Conversion-Tracking",
                    "Landingpage-Abstimmung",
                    "A/B-Testing",
                    "Laufende Optimierung",
                    "Klickpreis-Analyse",
                    "Lead-Qualität",
                    "Reporting",
                    "Remarketing",
                    "Tracking über Google Tag Manager",
                    "GA4-Integration",
                    "Kampagnenberatung",
                ],
            },
            {
                number: "07",
                title: "Social Media & Content Marketing",
                items: [
                    "Instagram Content",
                    "Social-Media-Strategie",
                    "Post-Design",
                    "Carousel-Design",
                    "Reels-Konzepte",
                    "Story-Design",
                    "Content-Kalender",
                    "Kampagnenideen",
                    "Visuelle Serien",
                    "Social-Media-Guidelines",
                    "Community-orientierte Inhalte",
                    "Content für Arztpraxen",
                    "Content für Restaurants",
                    "Content für E-Commerce",
                    "Content für Premium-Brands",
                    "Text & Caption-Erstellung",
                    "Social-Media-Werbung",
                    "Meta Ads Vorbereitung",
                ],
            },
            {
                number: "08",
                title: "Branding & Visual Identity",
                items: [
                    "Logo Design",
                    "Logo Redesign",
                    "Brand Identity",
                    "Brand Strategy",
                    "Farbsystem",
                    "Typografie",
                    "Bildsprache",
                    "Markenwelt",
                    "Corporate Design",
                    "Brand Guidelines",
                    "Social-Media-Look",
                    "Icon-Systeme",
                    "Grafische Elemente",
                    "Visuelle Richtung",
                    "Moodboards",
                    "Art Direction",
                    "Brand Refresh",
                    "Naming",
                    "Claim-Entwicklung",
                    "Markenpositionierung",
                ],
            },
        ],
    },
    {
        number: "03",
        title: "Sichtbarkeit, Marketing & Content",
        video: "/services/services-03.mp4",
        poster: "/images/services-03-poster.webp",
        groups: [
            {
                number: "09",
                title: "Foto, Video & Content Production",
                items: [
                    "Business-Fotografie",
                    "Portrait-Fotografie",
                    "Team-Fotografie",
                    "Praxis-Fotografie",
                    "Restaurant-Fotografie",
                    "Produktfotografie",
                    "Beauty-Fotografie",
                    "Automotive Content",
                    "Video-Produktion",
                    "Imagefilme",
                    "Reels-Produktion",
                    "Social-Media-Clips",
                    "Website-Videos",
                    "Behind-the-Scenes",
                    "Produktinszenierung",
                    "Content-Shooting",
                    "Postproduktion",
                    "Retusche",
                    "Color Grading",
                    "Cinematic Visuals",
                ],
            },
            {
                number: "10",
                title: "Motion, 3D & AI Visuals",
                items: [
                    "AI-Bildwelten",
                    "AI-Kampagnenvisuals",
                    "AI-Produktinszenierung",
                    "3D Visuals",
                    "Motion Design",
                    "Animationen",
                    "Hero-Animationen",
                    "Website-Motion",
                    "Social-Media-Animationen",
                    "Kling AI Konzepte",
                    "Video-Prompts",
                    "Storyboard-Entwicklung",
                    "Cinematic Key Visuals",
                    "Produkt-Renderings",
                    "Surreale Markenwelten",
                    "Digitale Mood-Kampagnen",
                    "Creative Direction für AI Content",
                ],
            },
            {
                number: "11",
                title: "Print Design & Offline Medien",
                items: [
                    "Visitenkarten",
                    "Flyer",
                    "Broschüren",
                    "Praxisunterlagen",
                    "Preislisten",
                    "Menükarten",
                    "Gutscheine",
                    "Plakate",
                    "Roll-ups",
                    "Briefpapier",
                    "Geschäftsausstattung",
                    "Packaging Design",
                    "Etiketten",
                    "Print-Kampagnen",
                    "Editorial Design",
                    "PDF-Präsentationen",
                    "Angebotsunterlagen",
                    "Brand-Materialien für Kundenkontakt",
                ],
            },
            {
                number: "12",
                title: "AI, Automatisierung & digitale Workflows",
                items: [
                    "AI-Workflows",
                    "Chatbots",
                    "Automatisierte Formulare",
                    "Lead-Automatisierung",
                    "E-Mail-Automationen",
                    "CRM-Anbindungen",
                    "Content-Automation",
                    "Interne Tools",
                    "KI-gestützte Texterstellung",
                    "KI-gestützte Bildkonzepte",
                    "Automatische Anfrageprozesse",
                    "Automatisierte Benachrichtigungen",
                    "Terminprozesse",
                    "Datenstrukturierung",
                    "No-Code-Automationen",
                    "Prozessberatung",
                    "Digitale Assistenzsysteme",
                ],
            },
        ],
    },
    {
        number: "04",
        title: "AI, Motion & Automation",
        video: "/services/services-04.mp4",
        poster: "/images/services-04-poster.webp",
        groups: [
            {
                number: "13",
                title: "Tracking, Analytics & Conversion",
                items: [
                    "Google Analytics 4",
                    "Google Tag Manager",
                    "Conversion-Tracking",
                    "Event-Tracking",
                    "Telefon-Klick-Tracking",
                    "Mail-Klick-Tracking",
                    "WhatsApp-Klick-Tracking",
                    "Formular-Tracking",
                    "Consent Mode V2",
                    "Cookie-Banner-Integration",
                    "Kampagnen-Tracking",
                    "Landingpage-Analyse",
                    "Conversion-Optimierung",
                    "User-Verhalten",
                    "Reporting",
                    "Dashboard-Strukturen",
                    "Datenbasierte Optimierung",
                ],
            },
            {
                number: "14",
                title: "Wartung, Support & Betreuung",
                items: [
                    "Website-Wartung",
                    "WordPress Updates",
                    "Plugin-Updates",
                    "Sicherheitschecks",
                    "Backups",
                    "Technischer Support",
                    "Performance-Kontrolle",
                    "Content-Anpassungen",
                    "Fehlerbehebung",
                    "Hosting-Beratung",
                    "Domain-Setup",
                    "E-Mail-Setup",
                    "Cookie-Updates",
                    "SEO-Betreuung",
                    "Kampagnenbetreuung",
                    "Monatliche Optimierung",
                    "Langfristige Beratung",
                ],
            },
        ],
    },
];
