// Generated by scripts/sync-spline-assets.mjs — do not edit by hand.
// Run `npm run sync:spline` after re-publishing a scene in the Spline editor.

/**
 * Local paths to the self-hosted Spline scenes. The filenames carry a hash of
 * the scene contents, so next.config.ts can cache them immutably.
 */
export const SPLINE_SCENES = {
  /** homepage hero */
  'medusa': '/scenes/medusa-47ead05d.splinecode',
  /** agency page */
  'agency-2': '/scenes/agency-2-4f0e8494.splinecode',
  /** services */
  'cubes': '/scenes/cubes-111cea77.splinecode',
  /** projects hero */
  'projects-hero': '/scenes/projects-hero-95df70fa.splinecode',
  /** decorative torus */
  'torus': '/scenes/torus-86fa248d.splinecode',
} as const;

export type SplineSceneName = keyof typeof SPLINE_SCENES;

/**
 * Where @splinetool/runtime looks for its wasm assets. Setting this keeps the
 * runtime from falling back to unpkg.com / gstatic.com — see the header of
 * scripts/sync-spline-assets.mjs for what is and is not shipped there.
 */
export const SPLINE_WASM_PATH = '/spline-wasm';
